services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_TURNSTILE_SITE_KEY: ${NEXT_PUBLIC_TURNSTILE_SITE_KEY}
    image: 629143592903.dkr.ecr.us-east-1.amazonaws.com/da-website:latest
    ports:
      - "3000:3000"
    env_file:
      - path: .env
        required: false
    environment:
      - NODE_ENV=production
    restart: unless-stopped
